services:
  microservices-demo-mysql:
    image: mysql:5.7
    platform: linux/x86_64
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: users
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./microservices-demo-name-service/init.sql:/docker-entrypoint-initdb.d/init.sql

  microservices-demo-mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: birthdaydb
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  microservices-demo-name-service:
    build: ./microservices-demo-name-service
    ports:
      - "8000:8000"
    depends_on:
      - microservices-demo-mysql
    environment:
      DATABASE_URL: mysql+pymysql://microservices-demo-mysql:3306/users
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  microservices-demo-birthday-service:
    build: ./microservices-demo-birthday-service
    ports:
      - "8080:8080"
    depends_on:
      - microservices-demo-mongo
    environment:
      MONGO_URL: mongodb://microservices-demo-mongo:27017/birthdaydb

  microservices-demo-api-gateway:
    build: ./microservices-demo-api-gateway
    ports:
      - "4000:4000"
    depends_on:
      - microservices-demo-name-service
      - microservices-demo-birthday-service
    environment:
      NAME_SERVICE_URL: http://microservices-demo-name-service:8000
      BIRTHDAY_SERVICE_URL: http://microservices-demo-birthday-service:8080

  microservices-demo-frontend:
    build: ./microservices-demo-frontend
    ports:
      - "3000:80"
    depends_on:
      - microservices-demo-api-gateway

volumes:
  db_data:
    driver: local
  mongo-data:
    driver: local
