services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: users
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: birthdaydb
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  name-service:
    build: ./nameService
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    environment:
      DATABASE_URL: mysql+pymysql://root:password@mysql/users

  birthday-service:
    build: ./birthdayService
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      MONGO_URL: mongodb://mongo:27017/birthdaydb

  graphql-api:
    build: ./graphql-api
    ports:
      - "4000:4000"
    depends_on:
      - name-service
      - birthday-service
    environment:
      NAME_SERVICE_URL: http://name-service:8000
      BIRTHDAY_SERVICE_URL: http://birthday-service:8080

volumes:
  db_data:
    driver: local
  mongo-data:
    driver: local
